version: '3'

services:
  mbms:
    build: ./mbms
    environment: 
      LETSENCRYPT_HOST: pelican.hattadatta.com
      VIRTUAL_HOST: pelican.hattadatta.com
      DEBUG: "${DEBUG}"
      MODELS_PATH: "${MODELS_PATH}"
      DATA_TMP_PATH: "${DATA_TMP_PATH}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${MODELS_PATH}:${MODELS_PATH}"
      - "${DATA_TMP_PATH}:${DATA_TMP_PATH}"
    networks:
      - dss
      - didithilmy
  runner:
    build: ./runner
    environment: 
      LETSENCRYPT_HOST: kitten.hattadatta.com
      VIRTUAL_HOST: kitten.hattadatta.com
      DEBUG: "${DEBUG}"
      MBMS_URL: "http://mbms"
      DB_URL: "${DB_URL}"
    networks:
      - dss
      - didithilmy
      - dssext

networks:
  dss:
  didithilmy:
    external:
      name: didithilmy
  dssext:
    external:
      name: dss